Resources:
  streamlinkerfunctionServiceRoleE36D6F5E:
    Type: AWS::IAM::Role
    Properties:
      AssumeRolePolicyDocument:
        Statement:
          - Action: sts:AssumeRole
            Effect: Allow
            Principal:
              Service: lambda.amazonaws.com
        Version: "2012-10-17"
      ManagedPolicyArns:
        - Fn::Join:
            - ""
            - - "arn:"
              - Ref: AWS::Partition
              - :iam::aws:policy/service-role/AWSLambdaBasicExecutionRole
    Metadata:
      aws:cdk:path: rootstream-twitch-streamlink/streamlinkerfunction/ServiceRole/Resource
  streamlinkerfunction93C88E27:
    Type: AWS::Lambda::Function
    Properties:
      Code:
        S3Bucket:
          Ref: AssetParameters7d0b1d04751e420501a8ddd5cc6376a57d68de45308016e9f098bf04f24c7545S3BucketFEDB0A9B
        S3Key:
          Fn::Join:
            - ""
            - - Fn::Select:
                  - 0
                  - Fn::Split:
                      - "||"
                      - Ref: AssetParameters7d0b1d04751e420501a8ddd5cc6376a57d68de45308016e9f098bf04f24c7545S3VersionKey25D9107C
              - Fn::Select:
                  - 1
                  - Fn::Split:
                      - "||"
                      - Ref: AssetParameters7d0b1d04751e420501a8ddd5cc6376a57d68de45308016e9f098bf04f24c7545S3VersionKey25D9107C
      Handler: streamlinker.handler
      Role:
        Fn::GetAtt:
          - streamlinkerfunctionServiceRoleE36D6F5E
          - Arn
      Runtime: python3.8
    DependsOn:
      - streamlinkerfunctionServiceRoleE36D6F5E
    Metadata:
      aws:cdk:path: rootstream-twitch-streamlink/streamlinkerfunction/Resource
      aws:asset:path: /Users/sorob/Work/rootstream-twitch-streamlink/lambda
      aws:asset:property: Code
  streamlinkerF80F0953:
    Type: AWS::ApiGateway::RestApi
    Properties:
      Name: streamlinkerapi
    Metadata:
      aws:cdk:path: rootstream-twitch-streamlink/streamlinker/Resource
  streamlinkerCloudWatchRole96268B79:
    Type: AWS::IAM::Role
    Properties:
      AssumeRolePolicyDocument:
        Statement:
          - Action: sts:AssumeRole
            Effect: Allow
            Principal:
              Service: apigateway.amazonaws.com
        Version: "2012-10-17"
      ManagedPolicyArns:
        - Fn::Join:
            - ""
            - - "arn:"
              - Ref: AWS::Partition
              - :iam::aws:policy/service-role/AmazonAPIGatewayPushToCloudWatchLogs
    Metadata:
      aws:cdk:path: rootstream-twitch-streamlink/streamlinker/CloudWatchRole/Resource
  streamlinkerAccount52FE3645:
    Type: AWS::ApiGateway::Account
    Properties:
      CloudWatchRoleArn:
        Fn::GetAtt:
          - streamlinkerCloudWatchRole96268B79
          - Arn
    DependsOn:
      - streamlinkerF80F0953
    Metadata:
      aws:cdk:path: rootstream-twitch-streamlink/streamlinker/Account
  streamlinkerDeployment62CAA914a3b990a590d2b384c1319e9bc452875a:
    Type: AWS::ApiGateway::Deployment
    Properties:
      RestApiId:
        Ref: streamlinkerF80F0953
      Description: Automatically created by the RestApi construct
    DependsOn:
      - streamlinkerproxyANY39A06CB0
      - streamlinkerproxy00E886B9
      - streamlinkerANY9C0F1C3E
    Metadata:
      aws:cdk:path: rootstream-twitch-streamlink/streamlinker/Deployment/Resource
  streamlinkerDeploymentStageprodF1778155:
    Type: AWS::ApiGateway::Stage
    Properties:
      RestApiId:
        Ref: streamlinkerF80F0953
      DeploymentId:
        Ref: streamlinkerDeployment62CAA914a3b990a590d2b384c1319e9bc452875a
      StageName: prod
    Metadata:
      aws:cdk:path: rootstream-twitch-streamlink/streamlinker/DeploymentStage.prod/Resource
  streamlinkerproxy00E886B9:
    Type: AWS::ApiGateway::Resource
    Properties:
      ParentId:
        Fn::GetAtt:
          - streamlinkerF80F0953
          - RootResourceId
      PathPart: "{proxy+}"
      RestApiId:
        Ref: streamlinkerF80F0953
    Metadata:
      aws:cdk:path: rootstream-twitch-streamlink/streamlinker/Default/{proxy+}/Resource
  streamlinkerproxyANYApiPermissionrootstreamtwitchstreamlinkstreamlinker1A902BAFANYproxyD541C3E1:
    Type: AWS::Lambda::Permission
    Properties:
      Action: lambda:InvokeFunction
      FunctionName:
        Fn::GetAtt:
          - streamlinkerfunction93C88E27
          - Arn
      Principal: apigateway.amazonaws.com
      SourceArn:
        Fn::Join:
          - ""
          - - "arn:"
            - Ref: AWS::Partition
            - ":execute-api:"
            - Ref: AWS::Region
            - ":"
            - Ref: AWS::AccountId
            - ":"
            - Ref: streamlinkerF80F0953
            - /
            - Ref: streamlinkerDeploymentStageprodF1778155
            - /*/*
    Metadata:
      aws:cdk:path: rootstream-twitch-streamlink/streamlinker/Default/{proxy+}/ANY/ApiPermission.rootstreamtwitchstreamlinkstreamlinker1A902BAF.ANY..{proxy+}
  streamlinkerproxyANYApiPermissionTestrootstreamtwitchstreamlinkstreamlinker1A902BAFANYproxy35C84350:
    Type: AWS::Lambda::Permission
    Properties:
      Action: lambda:InvokeFunction
      FunctionName:
        Fn::GetAtt:
          - streamlinkerfunction93C88E27
          - Arn
      Principal: apigateway.amazonaws.com
      SourceArn:
        Fn::Join:
          - ""
          - - "arn:"
            - Ref: AWS::Partition
            - ":execute-api:"
            - Ref: AWS::Region
            - ":"
            - Ref: AWS::AccountId
            - ":"
            - Ref: streamlinkerF80F0953
            - /test-invoke-stage/*/*
    Metadata:
      aws:cdk:path: rootstream-twitch-streamlink/streamlinker/Default/{proxy+}/ANY/ApiPermission.Test.rootstreamtwitchstreamlinkstreamlinker1A902BAF.ANY..{proxy+}
  streamlinkerproxyANY39A06CB0:
    Type: AWS::ApiGateway::Method
    Properties:
      HttpMethod: ANY
      ResourceId:
        Ref: streamlinkerproxy00E886B9
      RestApiId:
        Ref: streamlinkerF80F0953
      AuthorizationType: NONE
      Integration:
        IntegrationHttpMethod: POST
        Type: AWS_PROXY
        Uri:
          Fn::Join:
            - ""
            - - "arn:"
              - Ref: AWS::Partition
              - ":apigateway:"
              - Ref: AWS::Region
              - :lambda:path/2015-03-31/functions/
              - Fn::GetAtt:
                  - streamlinkerfunction93C88E27
                  - Arn
              - /invocations
    Metadata:
      aws:cdk:path: rootstream-twitch-streamlink/streamlinker/Default/{proxy+}/ANY/Resource
  streamlinkerANYApiPermissionrootstreamtwitchstreamlinkstreamlinker1A902BAFANYA5A6E504:
    Type: AWS::Lambda::Permission
    Properties:
      Action: lambda:InvokeFunction
      FunctionName:
        Fn::GetAtt:
          - streamlinkerfunction93C88E27
          - Arn
      Principal: apigateway.amazonaws.com
      SourceArn:
        Fn::Join:
          - ""
          - - "arn:"
            - Ref: AWS::Partition
            - ":execute-api:"
            - Ref: AWS::Region
            - ":"
            - Ref: AWS::AccountId
            - ":"
            - Ref: streamlinkerF80F0953
            - /
            - Ref: streamlinkerDeploymentStageprodF1778155
            - /*/
    Metadata:
      aws:cdk:path: rootstream-twitch-streamlink/streamlinker/Default/ANY/ApiPermission.rootstreamtwitchstreamlinkstreamlinker1A902BAF.ANY..
  streamlinkerANYApiPermissionTestrootstreamtwitchstreamlinkstreamlinker1A902BAFANYB346FE57:
    Type: AWS::Lambda::Permission
    Properties:
      Action: lambda:InvokeFunction
      FunctionName:
        Fn::GetAtt:
          - streamlinkerfunction93C88E27
          - Arn
      Principal: apigateway.amazonaws.com
      SourceArn:
        Fn::Join:
          - ""
          - - "arn:"
            - Ref: AWS::Partition
            - ":execute-api:"
            - Ref: AWS::Region
            - ":"
            - Ref: AWS::AccountId
            - ":"
            - Ref: streamlinkerF80F0953
            - /test-invoke-stage/*/
    Metadata:
      aws:cdk:path: rootstream-twitch-streamlink/streamlinker/Default/ANY/ApiPermission.Test.rootstreamtwitchstreamlinkstreamlinker1A902BAF.ANY..
  streamlinkerANY9C0F1C3E:
    Type: AWS::ApiGateway::Method
    Properties:
      HttpMethod: ANY
      ResourceId:
        Fn::GetAtt:
          - streamlinkerF80F0953
          - RootResourceId
      RestApiId:
        Ref: streamlinkerF80F0953
      AuthorizationType: NONE
      Integration:
        IntegrationHttpMethod: POST
        Type: AWS_PROXY
        Uri:
          Fn::Join:
            - ""
            - - "arn:"
              - Ref: AWS::Partition
              - ":apigateway:"
              - Ref: AWS::Region
              - :lambda:path/2015-03-31/functions/
              - Fn::GetAtt:
                  - streamlinkerfunction93C88E27
                  - Arn
              - /invocations
    Metadata:
      aws:cdk:path: rootstream-twitch-streamlink/streamlinker/Default/ANY/Resource
  CDKMetadata:
    Type: AWS::CDK::Metadata
    Properties:
      Modules: aws-cdk=1.70.0,@aws-cdk/assets=1.71.0,@aws-cdk/aws-apigateway=1.71.0,@aws-cdk/aws-applicationautoscaling=1.71.0,@aws-cdk/aws-autoscaling-common=1.71.0,@aws-cdk/aws-certificatemanager=1.71.0,@aws-cdk/aws-cloudwatch=1.71.0,@aws-cdk/aws-codeguruprofiler=1.71.0,@aws-cdk/aws-ec2=1.71.0,@aws-cdk/aws-efs=1.71.0,@aws-cdk/aws-elasticloadbalancingv2=1.71.0,@aws-cdk/aws-events=1.71.0,@aws-cdk/aws-iam=1.71.0,@aws-cdk/aws-kms=1.71.0,@aws-cdk/aws-lambda=1.71.0,@aws-cdk/aws-logs=1.71.0,@aws-cdk/aws-route53=1.71.0,@aws-cdk/aws-s3=1.71.0,@aws-cdk/aws-s3-assets=1.71.0,@aws-cdk/aws-sqs=1.71.0,@aws-cdk/aws-ssm=1.71.0,@aws-cdk/cloud-assembly-schema=1.71.0,@aws-cdk/core=1.71.0,@aws-cdk/cx-api=1.71.0,@aws-cdk/region-info=1.71.0,jsii-runtime=Python/3.8.1
    Metadata:
      aws:cdk:path: rootstream-twitch-streamlink/CDKMetadata/Default
    Condition: CDKMetadataAvailable
Parameters:
  AssetParameters7d0b1d04751e420501a8ddd5cc6376a57d68de45308016e9f098bf04f24c7545S3BucketFEDB0A9B:
    Type: String
    Description: S3 bucket for asset "7d0b1d04751e420501a8ddd5cc6376a57d68de45308016e9f098bf04f24c7545"
  AssetParameters7d0b1d04751e420501a8ddd5cc6376a57d68de45308016e9f098bf04f24c7545S3VersionKey25D9107C:
    Type: String
    Description: S3 key for asset version "7d0b1d04751e420501a8ddd5cc6376a57d68de45308016e9f098bf04f24c7545"
  AssetParameters7d0b1d04751e420501a8ddd5cc6376a57d68de45308016e9f098bf04f24c7545ArtifactHash84458FC9:
    Type: String
    Description: Artifact hash for asset "7d0b1d04751e420501a8ddd5cc6376a57d68de45308016e9f098bf04f24c7545"
Outputs:
  streamlinkerEndpointAB0B8199:
    Value:
      Fn::Join:
        - ""
        - - https://
          - Ref: streamlinkerF80F0953
          - .execute-api.
          - Ref: AWS::Region
          - "."
          - Ref: AWS::URLSuffix
          - /
          - Ref: streamlinkerDeploymentStageprodF1778155
          - /
Conditions:
  CDKMetadataAvailable:
    Fn::Or:
      - Fn::Or:
          - Fn::Equals:
              - Ref: AWS::Region
              - ap-east-1
          - Fn::Equals:
              - Ref: AWS::Region
              - ap-northeast-1
          - Fn::Equals:
              - Ref: AWS::Region
              - ap-northeast-2
          - Fn::Equals:
              - Ref: AWS::Region
              - ap-south-1
          - Fn::Equals:
              - Ref: AWS::Region
              - ap-southeast-1
          - Fn::Equals:
              - Ref: AWS::Region
              - ap-southeast-2
          - Fn::Equals:
              - Ref: AWS::Region
              - ca-central-1
          - Fn::Equals:
              - Ref: AWS::Region
              - cn-north-1
          - Fn::Equals:
              - Ref: AWS::Region
              - cn-northwest-1
          - Fn::Equals:
              - Ref: AWS::Region
              - eu-central-1
      - Fn::Or:
          - Fn::Equals:
              - Ref: AWS::Region
              - eu-north-1
          - Fn::Equals:
              - Ref: AWS::Region
              - eu-west-1
          - Fn::Equals:
              - Ref: AWS::Region
              - eu-west-2
          - Fn::Equals:
              - Ref: AWS::Region
              - eu-west-3
          - Fn::Equals:
              - Ref: AWS::Region
              - me-south-1
          - Fn::Equals:
              - Ref: AWS::Region
              - sa-east-1
          - Fn::Equals:
              - Ref: AWS::Region
              - us-east-1
          - Fn::Equals:
              - Ref: AWS::Region
              - us-east-2
          - Fn::Equals:
              - Ref: AWS::Region
              - us-west-1
          - Fn::Equals:
              - Ref: AWS::Region
              - us-west-2

